// Generates src/data/visa.generated.ts from the maintained passport-index
// dataset (ilyankou/passport-index-dataset) + mledoze/countries for names.
// Run: node scripts/generate-visa.mjs
import { writeFileSync } from "node:fs";

const CSV_URL =
  "https://raw.githubusercontent.com/ilyankou/passport-index-dataset/master/passport-index-tidy-iso3.csv";
const COUNTRIES_URL =
  "https://raw.githubusercontent.com/mledoze/countries/master/countries.json";

/** Normalise a raw requirement value into a compact code. */
function encode(req) {
  const r = req.trim();
  if (r === "-1") return "H"; // same country
  if (/^\d+$/.test(r)) return `F:${r}`; // visa-free for N days
  switch (r.toLowerCase()) {
    case "visa free":
      return "F";
    case "visa on arrival":
      return "VOA";
    case "e-visa":
      return "EV";
    case "eta":
      return "ETA";
    case "visa required":
      return "R";
    case "no admission":
      return "X";
    default:
      return "R";
  }
}

async function main() {
  console.log("Fetching passport-index dataset…");
  const csv = await (await fetch(CSV_URL)).text();
  console.log("Fetching country names (mledoze)…");
  const mledoze = await (await fetch(COUNTRIES_URL)).json();

  // iso3 -> { iso2, name }, and iso2(upper) -> iso3
  const byIso3 = {};
  const iso2ToIso3 = {};
  for (const c of mledoze) {
    const iso3 = c.cca3;
    const iso2 = c.cca2;
    const name = c.name?.common ?? iso3;
    if (iso3) byIso3[iso3] = { iso2, name };
    if (iso2 && iso3) iso2ToIso3[iso2.toUpperCase()] = iso3;
  }

  const lines = csv.split("\n").slice(1).filter((l) => l.includes(","));
  const matrix = {}; // destIso3 -> { passportIso3: code }
  const passportSet = new Set();

  for (const line of lines) {
    const [passport, dest, ...rest] = line.split(",");
    const req = rest.join(",").trim();
    if (!passport || !dest) continue;
    passportSet.add(passport.trim());
    const d = dest.trim();
    (matrix[d] ??= {})[passport.trim()] = encode(req);
  }

  // Passport list for the "home country" dropdown.
  const passports = [...passportSet]
    .map((iso3) => ({
      iso3,
      iso2: byIso3[iso3]?.iso2 ?? "",
      name: byIso3[iso3]?.name ?? iso3,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  const out = `// AUTO-GENERATED by scripts/generate-visa.mjs — do not edit by hand.
// Source: ilyankou/passport-index-dataset (visa requirement matrix) +
// mledoze/countries (names / ISO codes). Requirement codes:
//   H = same country, F = visa-free (F:NN = NN days), VOA = visa on arrival,
//   EV = e-visa, ETA = electronic travel authorisation, R = visa required,
//   X = no admission.

export type Passport = { iso3: string; iso2: string; name: string };

export const passports: Passport[] = ${JSON.stringify(passports)};

export const iso2ToIso3: Record<string, string> = ${JSON.stringify(iso2ToIso3)};

// destinationISO3 -> { passportISO3: code }
export const visaMatrix: Record<string, Record<string, string>> = ${JSON.stringify(matrix)};

export function visaColumn(destIso3: string): { iso3: string; iso2: string; name: string; code: string }[] {
  const col = visaMatrix[destIso3] ?? {};
  return passports
    .map((p) => ({ ...p, code: col[p.iso3] ?? "R" }))
    .filter((p) => p.code !== "H");
}
`;

  const target = "src/data/visa.generated.ts";
  writeFileSync(target, out, "utf8");
  console.log(
    `Wrote ${target}: ${passports.length} passports, ${Object.keys(matrix).length} destinations.`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
