// AUTO-GENERATED by scripts/generate-cities.mjs — do not edit by hand.
// City list from GeoNames (cities15000); photos from Wikipedia where available.
// Data lives in cities.generated.json so tsc does not infer a 3k-member union.
import type { City } from "@/lib/types";
import { PHOTOS, unsplash } from "@/lib/images";
import rawJson from "./cities.generated.json";

type Gen = Omit<
  City,
  "heroImage" | "thumbnail" | "gallery" | "coordinates" | "attractionSlugs"
> & {
  heroKey: keyof typeof PHOTOS;
  galleryKeys: (keyof typeof PHOTOS)[];
  realPhoto: string | null;
  realGallery: string[];
  lat: number;
  lng: number;
};

const raw = rawJson as Gen[];

export const generatedCities: City[] = raw.map((c) => {
  const { heroKey, galleryKeys, realPhoto, realGallery, lat, lng, ...rest } = c;
  const pool = galleryKeys.map((k) => unsplash(PHOTOS[k], 1400));
  const hero = realPhoto ?? realGallery[0] ?? null;
  // Prefer real, subject-relevant photos; only fall back to stock when we have
  // no real imagery at all (so galleries never show unrelated pictures).
  // Wikimedia originals are normalized at runtime (sanitizeCityImages) so we
  // keep raw Commons URLs here for regenerate stability.
  const realImages = Array.from(new Set([...(hero ? [hero] : []), ...realGallery]));
  const gallery = realImages.length > 0 ? realImages.slice(0, 6) : pool;
  return {
    ...rest,
    coordinates: { lat, lng },
    heroImage: hero ?? unsplash(PHOTOS[heroKey], 2400),
    thumbnail: hero ?? unsplash(PHOTOS[heroKey], 900),
    gallery,
    attractionSlugs: [],
  };
});
